# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 597)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.First_Input = QtWidgets.QLabel(parent=self.centralwidget)
        self.First_Input.setGeometry(QtCore.QRect(20, 220, 81, 41))
        self.First_Input.setObjectName("First_Input")
        self.Second_Input = QtWidgets.QLabel(parent=self.centralwidget)
        self.Second_Input.setGeometry(QtCore.QRect(210, 220, 81, 41))
        self.Second_Input.setObjectName("Second_Input")
        self.Answer = QtWidgets.QLabel(parent=self.centralwidget)
        self.Answer.setGeometry(QtCore.QRect(130, 110, 171, 121))
        self.Answer.setObjectName("Answer")
        self.Clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Clear.setGeometry(QtCore.QRect(10, 470, 71, 41))
        self.Clear.setObjectName("Clear")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 270, 61, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 270, 61, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.multi_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.multi_2.setGeometry(QtCore.QRect(230, 470, 71, 41))
        self.multi_2.setObjectName("multi_2")
        self.Error1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error1.setGeometry(QtCore.QRect(70, 150, 171, 41))
        self.Error1.setObjectName("Error1")
        self.Error2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error2.setGeometry(QtCore.QRect(70, 150, 171, 41))
        self.Error2.setObjectName("Error2")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 380, 41, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 380, 41, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(140, 380, 41, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(200, 380, 41, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.First_Input.setText(_translate("MainWindow", "First Input"))
        self.Second_Input.setText(_translate("MainWindow", "Second Input"))
        self.Answer.setText(_translate("MainWindow", "Answer"))
        self.Clear.setText(_translate("MainWindow", "CLEAR"))
        self.multi_2.setText(_translate("MainWindow", "="))
        self.Error1.setText(_translate("MainWindow", "INVALID INPUT (# only)"))
        self.Error2.setText(_translate("MainWindow", "CANNOT DIVIDE BY ZERO"))
        self.radioButton.setText(_translate("MainWindow", "+"))
        self.radioButton_2.setText(_translate("MainWindow", "-"))
        self.radioButton_3.setText(_translate("MainWindow", "/"))
        self.radioButton_4.setText(_translate("MainWindow", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
